import Head from "next/head";
import { Footer } from "../../components/Footer";
import { Header } from "../../components/Header";
import { useRouter } from "next/router";
import { useEffect } from "react";
import { fazGet } from "../../services/api";

export default function Product() {
  const router = useRouter();

  useEffect(() => {
    if (typeof router.query.id != "undefined") {
  
      let url = "http://127.0.0.1:8000/api/product/list/" + router.query.id;

      console.log(url);

      fazGet(url);

    }
  });

  return (
    <div>
      <Head>
        <title>Ecommerce | Produto {router.query.id}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <Footer />
    </div>
  );
}
