import Head from "next/head";
import { Footer } from "../../components/Footer";
import { Header } from "../../components/Header";
import { ProductPresentation } from "../../components/ProductPresentation";
import { useRouter } from "next/router";
import { useEffect } from "react";
import { fazGet } from "../../services/api";
import { useState } from "react";

export default function Product() {
  const [dataProduct, setDataProduct] = useState();
  const router = useRouter();

  useEffect(() => {
    if (router.query.id) {
  
      let url = "http://127.0.0.1:8000/api/product/list/" + router.query.id;

      console.log(url);

      fazGet(url).then(data => setDataProduct(data));

    }
  } , [router]);

  return (
    <div>
      <Head>
        <title>Ecommerce | Produto {router.query.id}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <ProductPresentation product={dataProduct}/>
      <Footer />
    </div>
  );
}
